name: Kernel Build (marble)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl bc bison flex \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libssl-dev build-essential lld llvm \
            python3 python3-pip zip unzip cpio jq

      - name: Setup Clang (r563880b)
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86/clang-r563880b
          cd prebuilts-master/clang/host/linux-x86/clang-r563880b
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/67af9f576276f27363074c4388e2cf0963bab6df/clang-r563880b.tar.gz -O clang-r563880b.tar.gz
          tar -xf clang-r563880b.tar.gz
          rm clang-r563880b.tar.gz
          cd ../../../../../

      - name: Build Kernel (Image.gz)
        run: |
          export PATH=$(pwd)/prebuilts-master/clang/host/linux-x86/clang-r563880b/bin:$PATH
          make O=out ARCH=arm64 marble_defconfig
          make O=out ARCH=arm64 CC=clang -j$(nproc)

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: marble-kernel
          path: |
            out/arch/arm64/boot/Image.gz
            out/arch/arm64/boot/dts/**/*.dtb
            out/arch/arm64/boot/dtbo.img
