name: Kernel Build (marble)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl bc bison flex \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libssl-dev build-essential lld llvm \
            python3 python3-pip zip unzip cpio jq

      - name: Setup LLVM 21.0.0
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          cd prebuilts-master/clang/host/linux-x86
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-21.0.0/clang+llvm-21.0.0-x86_64-linux-gnu-ubuntu-22.04.tar.xz
