name: Kernel Build (marble)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git wget curl bc bison flex \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libssl-dev build-essential lld llvm \
            python3 python3-pip zip unzip cpio jq

      - name: Setup Clang (r563880b)
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          cd prebuilts-master/clang/host/linux-x86
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/67af9f576276f27363074c4388e2cf0963bab6df/clang-r563880b.tar.gz
          mkdir clang-r563880b
          tar -xf clang-r563880b.tar.gz -C clang-r563880b
          cd ../../../../
          echo "$(pwd)/prebuilts-master/clang/host/linux-x86/clang-r563880b/bin" >> $GITHUB_PATH

      - name: Build Kernel (Image.gz only)
        run: |
          mkdir -p out
          make O=out ARCH=arm64 gki_defconfig
          ./scripts/kconfig/merge_config.sh out/.config vendor/marble_GKI.config
          make O=out ARCH=arm64 CC=clang -j$(nproc) Image.gz

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          zip -r9 ../marble-kernel.zip ./*

      - name: Upload Kernel ZIP
        uses: actions/upload-artifact@v4
        with:
          name: marble-kernel-zip
          path: marble-kernel.zip
