name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git make clang lld llvm \
            gcc-aarch64-linux-gnu libc6-dev \
            device-tree-compiler bc bison flex libssl-dev \
            build-essential curl wget unzip

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: build/Image
